# Generated by Django 5.0.5 on 2024-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
